apiVersion: v1
kind: Secret
metadata:
  name: microsoft-oauth-secret
  namespace: ecatalog
type: Opaque
stringData:
  client-id: "a6822c5f-f140-4356-8778-5e821789c75e"
  client-secret: "u0L8Q~XduiIHtwxHYwJt-oyTBVwiX2YmRtoONbQF"
