apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    type: local
    app: database
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ecatalog/database"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
