apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-config
  namespace: ecatalog
data:
  microsoft-redirect-uri: "http://localhost:8080/api/auth/microsoft/callback"
  microsoft-tenant-id: "common"
