apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-config
  namespace: ecatalog
data:
  # Microsoft OAuth Configuration
  microsoft-redirect-uri: "http://localhost:8080/api/auth/microsoft/callback"
  microsoft-tenant-id: "common"
  
  catalog-url: "http://catalog.ecatalog.svc.cluster.local:8000"