apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: ecatalog
  labels:
    app: catalog
data:
  # Configurações do serviço Catalog
  SERVICE_NAME: "catalog"
  VERSION: "1.0.0"
  ENVIRONMENT: "production"
  CATALOG_PORT: "8000"
  
  # URL do Database interno (Pod 2)
  DATABASE_URL: "http://database-internal:8001"
  
  # URL do Authentication Service (mantém-se separado)
  AUTHENTICATION_URL: "http://authentication:8080"
  
  # Logging
  LOG_LEVEL: "INFO"
