apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ecatalog
data:
  # URL do API Gateway (service interno Kubernetes)
  VITE_API_URL: "http://api-gateway.ecatalog.svc.cluster.local:8000"
  frontend-url: "http://192.168.49.2:30300"
