apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ecatalog
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: E-Catalog Metrics
        type: simpod-json-datasource
        access: proxy
        url: http://metrics-exporter:9090
        isDefault: true
        jsonData:
          timeout: 60
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: ecatalog
data:
  dashboard.yml: |
    apiVersion: 1
    providers:
      - name: 'E-Catalog Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards